# https://mago.carthage.software/guide/configuration
php-version = "8.2"

[source]
paths = ["src/", "bin/"]
includes = ["vendor"]

[formatter]
print-width = 120
null-type-hint = "question"
inline-empty-classlike-braces = true
array-table-style-alignment = false
space-before-arrow-function-parameter-list-parenthesis = true
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
break-promoted-properties-list = false
always-break-named-arguments-list = false

[linter]
integrations = ["symfony"]

[linter.rules]
valid-docblock.enabled = true
literal-named-argument.enabled = false
prefer-arrow-function.enabled = false
prefer-first-class-callable.enabled = false
prefer-early-continue.enabled = false
prefer-static-closure.enabled = false
no-else-clause.enabled = false
